### ISSUE TITLE
Resizing the browser causes counter to start infinitely 

### ISSUE THREAD

**Issue by aaronculp-droneup** [pqina/tick#9]
I had a counter that initialized at 0, when I resize the browser or a user on iPhone scrolls left/right slightly the counter starts to count infinitely.

No errors in console on why this happens.. 

Here is my component:
`
import React, { useRef, useEffect } from "react";
import Tick from "@pqina/flip";
import "@pqina/flip/dist/flip.min.css";
import './index.css';

export const Flipr = ({ value }) => {
    const divRef = useRef();
    const tickRef = useRef();

    useEffect(() => {
        const currDiv = divRef.current;

        Tick.DOM.create(currDiv, {
            value,
            didInit: (tick) => {
                tickRef.current = tick;
            },
            view: {
                children: [
                    {
                        repeat: true,
                        root: "div",
                        style: ".flip",
                        transform: "step(1) -> arrive -> step(1)",
                        transition: "crossfade",
                        view: '',
                        children: [
                            {
                                view: "flip"
                            }
                        ]
                    }
                ]
            }
        });

        return () => Tick.DOM.destroy(tickRef.current);
    }, [value]);

    useEffect(() => {
        if (tickRef.current) {
            tickRef.current.value = value;
        }
    }, []);

    return (
        <div>
            <div ref={divRef} />
        </div>
    )
};
`

App.js:

`
 <Flipr value={0} />
`

package.json -- "@pqina/flip": "1.7.5",

**Comment by aaronculp-droneup** [comment]
only showing value=0 so show that no matter the value resizing the browser is root cause

**Comment by aaronculp-droneup** [comment]
fixed by updating 
      transform: "step(1) -> arrive -> step(1)", 
      to
       transform: "arrive(1, 1, false, true)",

**Comment by rikschennink** [comment]
@aaronculp-droneup sounds like it's fixed, I'll close the issue then.
